# Generated by Django 4.2 on 2023-09-14 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0002_bb__content_rendered_alter_bb_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='bb',
            name='archive',
            field=models.FileField(blank=True, upload_to='archives/'),
        ),
    ]
