# Generated by Django 4.2 on 2023-09-18 11:25

import bboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0004_alter_bb_archive'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bb',
            name='archive',
        ),
        migrations.AddField(
            model_name='bb',
            name='picture',
            field=models.ImageField(blank=True, upload_to=bboard.models.get_timestamp_path, verbose_name='Изображение'),
        ),
    ]
