# Generated by Django 4.2 on 2023-05-24 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0001_squashed_0004_alter_bb_price_alter_bb_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine',
            name='spares',
        ),
        migrations.DeleteModel(
            name='AdvUser',
        ),
        migrations.DeleteModel(
            name='Machine',
        ),
        migrations.DeleteModel(
            name='Spare',
        ),
    ]
