# Generated by Django 4.2 on 2023-05-24 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0005_remove_machine_spares_delete_advuser_delete_machine_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bb',
            options={'verbose_name': 'Объявление', 'verbose_name_plural': 'Объявления'},
        ),
        migrations.AlterOrderWithRespectTo(
            name='bb',
            order_with_respect_to='rubric',
        ),
    ]
