# Generated by Django 4.2 on 2023-05-29 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0009_alter_bb_options_alter_bb_order_with_respect_to'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bb',
            options={'ordering': ['-published', 'title'], 'verbose_name': 'Объявление', 'verbose_name_plural': 'Объявления'},
        ),
        migrations.AlterOrderWithRespectTo(
            name='bb',
            order_with_respect_to=None,
        ),
    ]
