# Generated by Django 4.2 on 2023-08-24 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_sms'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Machine',
        ),
        migrations.DeleteModel(
            name='Spare',
        ),
    ]
