# Generated by Django 4.2 on 2023-08-31 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0011_alter_bb_price'),
        ('testapp', '0005_privatemessage_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='RevRubric',
            fields=[
            ],
            options={
                'ordering': ['-name'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('bboard.rubric',),
        ),
        migrations.AlterModelOptions(
            name='privatemessage',
            options={'ordering': ['name']},
        ),
    ]
